openapi: 3.0.0
info:
  title: Hyperce Backend API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
  

servers:
  - url: http://localhost:3000/api/v1
    description:  Local server 
  - url: https://prod.com/
    description:  Pre Production server
  - url: https://test.com/
    description:  Production server
  

 
components:
  securitySchemes:
    ApiTokenss:        # arbitrary name for the security scheme
          
      type: http
      scheme: bearer
    
    ApiKey:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: apikey
      
paths:
  /auth/signup:
        post:
          tags:
            - Auth API
          summary: to register as a new user 
          requestBody:
            content:
              application/json:
                schema:      # Request body contents
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    firstName:
                      type: string
                    lastName:
                      type: string
                    address:
                      type: string
                    phoneNumber:
                      type: string
                  example:   # Sample object
                    email: daribdr@gmail.com
                    password : rambdr@123
                    firstName: Ram Bahadur
                    lastName : Khadka
                    address: Teku
                    phoneNumber : 9861584727
          responses:
            201:
              description: Created

  /auth/login:
    post:
      tags:
        - Auth API
      summary: Login 
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:   # Sample object
                email: haribdr@gmail.com
                password : rambdr@123
                
      responses:
        201:
          description: Created

  /products/:
        get:
          tags:
            - Products API
          summary: to get all products
          responses:
            201:
              description: 
  /products/{productId}:
        get:
          tags:
            - Products API
          summary: to get all products
          parameters:
            - in: path
              name: productId
              schema:
                type: string
              required: true
          responses:
            201:
              description: 
